project:
  type: book
  output-dir: output/book/
book:
  title: "The Big Book"
  author: 
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  chapters:
    - index.qmd
    - part: "w-python-numpy-grundlagen"
      chapters:
        - books/w-python-numpy-grundlagen/
    - part: "a-auswertung_fds_daten"
      chapters:
        - books/a-auswertung_fds_daten/
format:
  html:
    theme: flatly
    toc: true
    toc-depth: 2
  pdf:
    number-sections: true
